### ISSUE TITLE
Extend drawing API to draw more shapes

### ISSUE THREAD

**Issue by SunnieShine** [SunnieShine/Sudoku#356]
The goal is to allow APIs drawing more shapes onto a sudoku image, even variant sudoku elements such as diagonals, dots, comparison signs and so on.

> **Note**
> This issue may list some members that they are not appeared in standard sudoku rules, but they will be really useful on drawing, so I will plan to support them in API.

## Gallery

* [x] Embedded
  - [x] Single cell
    - [x] #365
    - [x] #366
    - [x] #367
    - [x] #368 (Triangles & Rectangle)
    - [x] #369
    - [x] #370
    - [x] #378
    - [x] Corner mark
      - [x] #377 (for diagonal-touched directions)
      - [x] #379 (for all surrounding directions)
      - [x] #381 (for adjacent directions)
    - [x] Other shapes
      - [x] #371
      - [x] #372
      - [x] #373
      - [x] #374
      - [x] #375
      - [x] #380
  - [x] Adjacent cell
    - [x] #357
    - [x] #358
    - [x] #359
    - [x] #360
    - [x] #361
  - [x] 2x2 square cell
    - [x] #362
    - [x] #363
    - [x] #364 (White dots for clockwise and black dots for counterclockwise)
    - [x] #376
* [x] Outside
  - [x] #392
  - [x] #393
* [ ] Grouped
  - [x] #383
  - [x] #386
  - [x] #387
  - [x] #388
  - [x] #389
  - [x] #390
  - [x] #391
  - [ ] Killer Cage
  - [ ] Arrow
  - [ ] Thermometer
* [x] [To be added]

**Comment by SunnieShine** [comment]
This issue is nearly completed. I'll close it and then implement last items with my pace.
