### ISSUE TITLE
Implement filter type that can automatically filters the generated puzzles

### ISSUE THREAD

**Issue by SunnieShine** [SunnieShine/Sudoku#543]
Today we don't have a mechanism to filter generated puzzles, but use a heavy `if` statement to filter puzzles.

I want to introduce a type called `GeneratedPuzzleFilter` to filter generated puzzles automatically, avoiding heavy `if` statements, to make the read-ability better.

## To-do list

- [x] Introduce types
  - [x] Project `Sudoku.Strategying`
    - [x] Namespace `Sudoku.Strategying.Validation`: validation APIs
      - [x] Type `enum ValidationFailedReason`
      - [x] Type `enum ValidationFailedSeverity`
      - [x] Type `record ValidationResult`
    - [x] Namespace `Sudoku.Strategying.Constraints`: Filtering APIs (I just don't like the word "filter" so I change the word into another one)
      - [x] Type `abstract class Constraint`
        - [x] Member `abstract ValidationResult`
        - [x] Member `abstract CheckingProperties`
        - [x] Member `abstract Check`
        - [x] Member `abstract Equals`, `abstract GetHashCode` and `abstract ToString`
        - [x] Member `virtual ConflictWith`
        - [x] Member `operator ==` and `operator !=`
        - [x] JSON serialization attributes
          - [x] `[JsonPolymorphic]`
          - [x] `[JsonDerivedType]`
      - [x] Derived constraints
      - [x] Confliction APIs
- [x] UI change
  - [x] Page addition
  - [x] Update UI
  - [x] Relates code to generating operation
  - [x] Miscellaneous
- [x] ~~Step traits: Sets for the traits for technique `Step` instances~~ (Separate issue)
